### PR TITLE
Xamui

### PR DESCRIPTION
**Pull request by nateforsyth**
Addition of GetLocation Xamarin GUI

Implementation hasn't changed, however you can compile and deploy this to a dev enabled smart phone.

### CODE REVIEW

**Comment by RaySingerNZ** [comment]
Hi Nathan, thanks for your pull request. I'm looking forward to downloading the code and trying it out. Can't wait to see it working with a UI.

I'll actually close this pull request (sorry!), and set up a new repo for the Xamarin/WundergroundNetLib combined project. Then this repo can stand alone so the library can be worked on independently. I'll then plug away and get the new version of the library up (at least enough so John can help me out on it too) and you can bring the new version of the library into the Xamarin project as it is developed.

Again, can't wait to try the Xamarin project out and get more familiar with that technology! Cheers!

**Comment by RaySingerNZ** [comment]
@nateforsyth I have set up the combined Library and Xamarin repository here: https://github.com/MorphicDev/WundergoundNetLib_XamarinUI

If you could fork that and send through a pull request that contains your code I'll merge that in.

Thanks man.

**Comment by nateforsyth** [comment]
No problem, I'll keep working on the repository I've forked and make some
progress over the weekend

**Comment by RaySingerNZ** [comment]
Awesome thanks @nateforsyth I'll let you know how if I make any progress too.

**Pull request closed without merging**
